repos:
  # Taken from the official docs: https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
  # Taken from the official docs: https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [ python ]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        args: [ --config=pyproject.toml ]
