data: ./datasets/nuscenes.yaml
model: ./models/point_frustums.yaml

trainer:
  default_root_dir: training
  max_epochs: 16
  log_every_n_steps: 5
  accumulate_grad_batches: 4
  #gradient_clip_val: 50
  #gradient_clip_algorithm: norm
  check_val_every_n_epoch: 1
  callbacks:
    - LearningRateMonitor
    #- RichProgressBar
    - class_path: point_frustums.callbacks.WeightInitLSUV
      init_args:
        init_types: [ Linear, Conv1d, Conv2d ]
        verbose: True
    - class_path: point_frustums.callbacks.GradientClipping
      init_args:
        clip_value: 1.0
    #- point_frustums.callbacks.CreateNuScenesSubmission
    #- class_path: point_frustums.callbacks.ModelWeightsFromCheckpoint
    #  init_args:
    #    checkpoint_path: training_logs/lightning_logs/version_47/checkpoints/epoch=6-step=6160.ckpt
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: training_logs
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: point_frustums
        save_dir: training_logs
        offline: False

seed_everything: 42