data: ./datasets/nuscenes.yaml
model: ./models/point_frustums.yaml

trainer:
  default_root_dir: training
  max_epochs: 1
  log_every_n_steps: 2
  accumulate_grad_batches: 5
  gradient_clip_val: 10
  gradient_clip_algorithm: norm
  callbacks: [ LearningRateMonitor, RichProgressBar, point_frustums.callbacks.CreateNuScenesSubmission ]
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: training_logs
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: point_frustums
        save_dir: training_logs
        offline: True